### PR TITLE
Hotfix RDS DBInstance With ClusterIdentifier

### LINKED ISSUE #183: Incorrect flagging of encrypted RDS clusters
When you set the AWS:RDS:DBCluster 'StorageEncrypted' property to 'true', it encrypts all instances in the cluster. cfn_nag is reporting a violation on each of the instances in the cluster, "RDS DBInstance should have StorageEncrypted enabled" even though this is not required when you configure an rds cluster.

### PR DESCRIPTION
**Pull request by byronic**
Closes #183; RDS database instances inherit the cluster's encryption status (if they are part of a cluster); fixes a false positive on database instance encryption in cases where a cluster identifier was present

### CODE REVIEW

File: lib/cfn-nag/custom_rules/RDSDBInstanceStorageEncryptedRule.rb [hunk 1]
```diff
@@ -20,8 +20,11 @@ def audit_impl(cfn_model)
     resources = cfn_model.resources_by_type('AWS::RDS::DBInstance')
 
     violating_instances = resources.select do |instance|
-      instance.storageEncrypted.nil? ||
-        instance.storageEncrypted.to_s.casecmp('false').zero?
+      instance.dBClusterIdentifier.nil? &&
+        (
+          instance.storageEncrypted.nil? ||
+          instance.storageEncrypted.to_s.casecmp('false').zero?
```
Comment (erickascic) [inline lib/cfn-nag/custom_rules/RDSDBInstanceStorageEncryptedRule.rb]: we should have an empty? predicate for this to drop the CCM

**Comment by erickascic** [comment]
BTW, a philosophical nit - we don't need no stinkin' "hot fixes".  all changes are equal and should be relatively small to cause a release as long as tests pass
